micronaut:
  application:
    name: keymanager
    server:
      port: ${SERVER_PORT:8080}
      router:
        static-resources:
          swagger:
            paths: classpath:META-INF/swagger
            mapping: /swagger/**

grpc:
  client:
    plaintext: true
    max-retry-attempts: 10
  channels:
    keyManagerGrpc:
      address: 'localhost:50051'

